
from pydantic import BaseModel, Field
from typing import List, Optional

class AgentResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the agent")
    sources: List[str] = Field(default=[], description="List of sources used to generate the answer")
    execution_time: float = Field(..., description="Time taken to execute the request in seconds")
